version: '3'

services:
  copilot-gpt4-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      #- COPILOT_TOKEN=gnu_xxxxx
    ports:
      - 8080:8080
    restart: unless-stopped
    container_name: copilot-gpt4-service
