apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "copilot-gpt4-service.fullname" . }}
  labels:
    {{- include "copilot-gpt4-service.labels" . | nindent 4 }}
data:
{{- range $k,$v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
  {{- if .Values.persistent.cache.enabled }}
  CACHE: "true"
  CACHE_DIR: {{ .Values.persistent.cache.mountPath | quote }}
  {{- end }}