apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "copilot-gpt4-service.fullname" . }}
  labels:
    {{- include "copilot-gpt4-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "copilot-gpt4-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "copilot-gpt4-service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "copilot-gpt4-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "copilot-gpt4-service.fullname" . }}
                optional: true
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          {{- if .Values.persistent.cache.enabled }}
          volumeMounts:
            - name: {{ .Values.persistent.cache.name }}
              mountPath: {{ .Values.persistent.cache.mountPath }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.persistent.cache.enabled }}
      volumes:
        {{- if eq .Values.persistent.cache.type "pvc" }}
        - name: {{ .Values.persistent.cache.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistent.cache.pvc.claimName }}
        {{- else if eq .Values.persistent.cache.type "hostPath" }}
        - name: {{ .Values.persistent.cache.name }}
          hostPath:
            path: {{ .Values.persistent.cache.hostPath.path }}
            type: {{ .Values.persistent.cache.hostPath.type }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
